import os
from dotenv import load_dotenv

load_dotenv()

# ── Paths ─────────────────────────────────────────────────────────────────────
DOCUMENTS_FOLDER = "documents"
FAISS_INDEX_PATH = "faiss_index"
IMAGES_FOLDER    = "pdf_images"      # extracted PDF figures (local only)

# ── Embedding — Level 1 upgrade ───────────────────────────────────────────────
# BAAI/bge-small-en-v1.5 : better semantic quality than all-MiniLM, still lightweight
EMBEDDING_MODEL = "BAAI/bge-small-en-v1.5"

# ── Chunking ──────────────────────────────────────────────────────────────────
CHUNK_SIZE    = 1200
CHUNK_OVERLAP = 200

# ── Retrieval — Level 2 upgrade ───────────────────────────────────────────────
TOP_K_RETRIEVAL = 10        # docs fetched by hybrid search before reranking
TOP_K_RERANKED  = 6         # docs kept after CrossEncoder reranking (increased for complex questions)

# BM25 + FAISS weights in the ensemble (must sum to 1.0)
BM25_WEIGHT  = 0.4
FAISS_WEIGHT = 0.6

# CrossEncoder reranker model
RERANKER_MODEL = "cross-encoder/ms-marco-MiniLM-L-6-v2"

# ── Multi-query — Level 3 upgrade ─────────────────────────────────────────────
MULTI_QUERY_VARIANTS = 2    # extra query variants generated by the LLM

# ── Groq ──────────────────────────────────────────────────────────────────────
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")

AVAILABLE_MODELS = [
    "llama-3.3-70b-versatile",
    "llama-3.1-8b-instant",
    "mixtral-8x7b-32768",
    "gemma2-9b-it",
]
DEFAULT_MODEL       = AVAILABLE_MODELS[0]
DEFAULT_TEMPERATURE = 0.2
